import { jest } from '@jest/globals'

export const createMockSupabaseClient = () => ({
  auth: {
    getUser: jest.fn(),
    signOut: jest.fn(),
  },
  from: jest.fn().mockReturnThis(),
  select: jest.fn().mockReturnThis(),
  insert: jest.fn(),
  update: jest.fn(),
  delete: jest.fn(),
  eq: jest.fn(),
  in: jest.fn(),
  or: jest.fn(),
  and: jest.fn(),
  single: jest.fn(),
  order: jest.fn(),
  limit: jest.fn(),
  range: jest.fn(),
  match: jest.fn(),
  neq: jest.fn(),
  gt: jest.fn(),
  gte: jest.fn(),
  lt: jest.fn(),
  lte: jest.fn(),
  is: jest.fn(),
  contains: jest.fn(),
  containedBy: jest.fn(),
  overlaps: jest.fn(),
  textSearch: jest.fn(),
  filter: jest.fn(),
  not: jest.fn(),
  ilike: jest.fn(),
  like: jest.fn(),
  between: jest.fn(),
  maybeSingle: jest.fn(),
  count: jest.fn(),
  then: jest.fn(),
  catch: jest.fn(),
  finally: jest.fn(),
})
